export const FETCH_COURSE_DETAIL_REQUEST = 'FETCH_COURSE_DETAIL_REQUEST'
export const FETCH_COURSE_DETAIL_SUCCESS = 'FETCH_COURSE_DETAIL_SUCCESS'
export const FETCH_COURSE_DETAIL_FAIL = 'FETCH_COURSE_DETAIL_FAIL'